### ISSUE TITLE
makefile doesn't build

### ISSUE THREAD

**Issue by joe-lawrence** [gwencasey96/AllegroVivace#1]
From the make manual, [What a Rule Looks Like](https://www.gnu.org/software/make/manual/html_node/Rule-Introduction.html#Rule-Introduction):
```
target : prerequisites
        recipe
```
In this case, the makefile could use **hello** as the target and **hello.c** as the prerequisite.  (gcc knows how to go from .c source to target, so we don't need an intermediate .o file just yet.)  The **recipe** would be the entire `gcc ...` line from the [Quickstart guide](https://github.com/liballeg/allegro_wiki/wiki/Quickstart#linux).

**Comment by joe-lawrence** [comment]
Fixed by commit 2e809f7c.

In the future, you can add a line like "Fixes: #1" to the commit message, github should automagically close the issue when it's committed.

Also, to review it's easier to markup changes as pull requests.

**Comment by joe-lawrence** [comment]
Ooops, I just tried the makefile and realize that it doesn't work.  Minor typos:
```
        $(cc) hello.c -o hello $(pkg-config allegro-5 allegro_font-5 --libs --cflags)
          ^^ lowercase         ^ missing extra $
```
1. Capitalizing `$CC` is needed as the variables are case sensitive
2. Not so intuitive, but shell command substitution requires an extra `$` to instruct make to **not** expand it (as a make variable or function call) and just pass to the shell.  So it should be `$$(pkg-config ... )`

**Comment by gwencasey96** [comment]
fixed
