### ISSUE TITLE
phase 2: multiple source files

### ISSUE THREAD

**Issue by joe-lawrence** [gwencasey96/AllegroVivace#6]
Creating makefiles for single source projects is a bit of an overkill, so let's start adding more sources to better demonstrate the power of make.

The smallest change we can probably make is to pull these calls out of `hello.c`:
```c
    al_init();
    al_install_keyboard();
```
and into their own `startup()` function in a new file called `util.c`. 

```c
#include <allegro5/allegro5.h>

void startup(void)
{
    al_init();
    al_install_keyboard();
}
```
A extra steps that will be required:
- A new header file `util.h` that prototypes `startup()` so that...
- `hello.c` can include the new header file and...
- `hello.c :: main()` should now call `startup()` in place of those functions

Doing this is going to break the build, so we'll need to update the makefile accordingly (this step might be easier to discuss, but feel free to research/attempt).

The first step in figuring out the makefile is to figure out how to do it by hand.  The most straightforward way would be in steps like:
``` bash
# Create intermediate object files (binary code, but we can't 
# run them as they are not complete programs)
% gcc -c hello.c -o hello.o
% gcc -c util.c  -o util.o
       |            |
       |             --- output to an object file
        ---------------- the -c option says not to run the linker

# Use gcc to link everything together so we have a binary
# we can run
% gcc $(pkg-config allegro-5 allegro_font-5 --libs --cflags) \
      hello.o util.o -o hello
      |       |         |
      |       |          --- final binary =
       --------------------- linking of object files, as well
                             as the allegro libraries as reported
                             by the pkg-config command

```
To update the makefile, we'll need to be a little more detailed about the dependencies to build `hello`.  For our first pass, we can setup three target / dependency / recipe sets:
- `hello` is built from `hello.o` and `util.o`
- `hello.o` depends on `hello.c` and `util.h`
- `util.o` depends on `util.c`

**Comment by gwencasey96** [comment]
commenting out original with just one file and putting new logic for utils in same file. Not sure if there's a better way to do this with multiple makefiles
